easy_admin:
  site_name: 'Administrace'
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: 'username' }
          - { property: 'email' }
          - property: 'hasRoleAdmin'
            label: 'Is admin?'
            type: choice
            type_options:
              choices:
                'No': 'No'
                'Yes': 'Yes'